name: Fork Docker CI

on:
  workflow_call:
    inputs:
      registry-internal:
        type: string
        required: true
      registry-public:
        type: string
        required: true
      service-account-username:
        type: string
        required: true
      service-account-email:
        type: string
        required: true
      # TODO think if we can pass a list of parameters to matrix them out (like in sriov-operator case)
      component-name:
        type: string
        required: true
      component-image:
        type: string
        required: true
      component-dockerfile:
        type: string
        required: true
    secrets:
      registry-username:
        required: true
      registry-token:
        required: true
      cicd-gh-token:
        required: true

jobs:
  determine_docker_registry_and_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - if: github.ref_type == 'branch'
        name: Determine docker registry and tag (when git branch)
        run: |
          echo DOCKER_REGISTRY=${{ inputs.registry-internal }} | tee -a $GITHUB_ENV
          echo DOCKER_TAG=$(git rev-parse --short HEAD) | tee -a $GITHUB_ENV  # short git commit hash
      - if: github.ref_type == 'tag'
        name: Determine docker registry and tag (when git tag)
        run: |
          echo DOCKER_REGISTRY=$(echo ${{ github.ref_name }} | sed 's/network-operator-//' | grep -q '-' && echo ${{ inputs.registry-internal }} || echo ${{ inputs.registry-public }}) | tee -a $GITHUB_ENV  # use public registry only when release tag has no '-beta*' or '-rc*' suffix
          echo DOCKER_TAG=${{ github.ref_name }} | tee -a $GITHUB_ENV
      - name: Store docker registry and tag for following jobs
        id: store-docker-registry-and-tag
        run: |
          echo DOCKER_REGISTRY=$DOCKER_REGISTRY >> $GITHUB_OUTPUT
          echo DOCKER_TAG=$DOCKER_TAG >> $GITHUB_OUTPUT
    outputs:
      docker_registry: ${{ steps.store-docker-registry-and-tag.outputs.DOCKER_REGISTRY }}
      docker_tag: ${{ steps.store-docker-registry-and-tag.outputs.DOCKER_TAG }}

  build_and_push_images:
    needs: determine_docker_registry_and_tag
    runs-on: ubuntu-latest
    env:
      BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le
      DOCKER_REGISTRY: ${{ needs.determine_docker_registry_and_tag.outputs.docker_registry }}
      DOCKER_TAG: ${{ needs.determine_docker_registry_and_tag.outputs.docker_tag }}
    # TODO think about how to achieve that with input parameters
    #    strategy:
    #      matrix:
    #        include:
    #          - component: operator
    #            image_name: sriov-network-operator
    #            dockerfile: Dockerfile
    #          - component: config-daemon
    #            image_name: sriov-network-operator-config-daemon
    #            dockerfile: Dockerfile.sriov-network-config-daemon
    #          - component: webhook
    #            image_name: sriov-network-operator-webhook
    #            dockerfile: Dockerfile.webhook
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-token }}
      - uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
          context: .
          file: ${{ inputs.component-dockerfile }}
          tags: ${{ env.DOCKER_REGISTRY }}/${{ inputs.component-image }}:${{ env.DOCKER_TAG }}
          # TODO think about how to achieve that with input parameters
          #          file: ${{ matrix.dockerfile }}
          #          tags: ${{ env.DOCKER_REGISTRY }}/${{ matrix.image_name }}:${{ env.DOCKER_TAG }}
          push: true

  update_network_operator_values:
    needs:
      - determine_docker_registry_and_tag
      - build_and_push_images
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ needs.determine_docker_registry_and_tag.outputs.docker_registry }}
      DOCKER_TAG: ${{ needs.determine_docker_registry_and_tag.outputs.docker_tag }}
      GH_TOKEN: ${{ secrets.cicd-gh-token }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}-fork
          token: ${{ secrets.cicd-gh-token }}
      - name: Determine base branch
        run: |
          if [[ "${{ github.ref_type }}" == "branch" || "${{ github.ref_name }}" == *"beta"* ]]; then  # branch commits and beta tags update values on network-operator's *master* branch
            echo BASE_BRANCH=master | tee -a $GITHUB_ENV
          else  # GA and `-rc.` tags update values on network-operator's respective *release* branches
            release_branch=$(echo ${{ github.ref_name }} | sed -E 's/^network-operator-([0-9]+\.[0-9]+).+/v\1.x/')  # example: transforms "network-operator-25.1.0-beta.2" to "v25.1.x"
            echo BASE_BRANCH=$release_branch | tee -a $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/network-operator
          ref: ${{ env.BASE_BRANCH }}
          token: ${{ secrets.cicd-gh-token }}
          path: network-operator-fork
      - name: Create PR to update image tags in network-operator values
        env:
          COMMIT_MESSAGE: "cicd: update ${{ github.repository }} images tags to ${{ env.DOCKER_TAG }} in chart values"
        run: |
          cd network-operator-fork

          git config user.name  ${{ inputs.service-account-username }}
          git config user.email ${{ inputs.service-account-email }}

          git checkout -b feature/update-${{ github.repository }}-tags-to-${{ env.DOCKER_TAG }}

          # TODO helm chart is a specific case, needs additional work
          #          rm -rf deployment/network-operator/charts/sriov-network-operator/*
          #          cp -r ../sriov-network-operator-fork/deployment/sriov-network-operator-chart/* deployment/network-operator/charts/sriov-network-operator/
          #          # we *don't* copy `Chart.yaml` with the files below, because network-operator's `Chart.yaml` refers to the SR-IOV chart name with a hardcoded version.
          #          git checkout -- deployment/network-operator/charts/sriov-network-operator/Chart.yaml

          yq -i '.${{ inputs.component-name }}.repository = "${{ env.DOCKER_REGISTRY }}"'  hack/release.yaml
          yq -i '.${{ inputs.component-name }}.version    = "${{ env.DOCKER_TAG }}"'       hack/release.yaml
          make release-build

          if ! git diff --color --unified=0 --exit-code; then
            git add deployment/network-operator/charts/sriov-network-operator
            git add -u
            git commit -sam "$COMMIT_MESSAGE"
            git push -f -u origin feature/update-${{ github.repository }}-tags-to-${{ env.DOCKER_TAG }}
            gh pr create \
              --repo ${{ github.repository_owner }}/network-operator \
              --base $BASE_BRANCH \
              --head $(git branch --show-current) \
              --title "$COMMIT_MESSAGE" \
              --body "Created by the *${{ github.job }}* job."
          fi