name: Fork Docker CI

on:
  workflow_call:
    inputs:
      registry-internal:
        type: string
        required: true
      registry-public:
        type: string
        required: true
      service-account-username:
        type: string
        required: true
      service-account-email:
        type: string
        required: true
      components:
        description: "List of components that require image build and version update. Should be a json list of the format: [{'name': 'componentA', 'imageName': 'imageA', 'dockerfile': 'Dockerfile'}]"
        type: string
        required: true
      # Testing parameters
      ref-name:
        description: "Name of the git ref to use if github object is not available"
        type: string
        required: false
      ref-type:
        description: "Type of the git ref to use if github object is not available"
        type: string
        required: false
      network-operator-repo:
        description: "Network Operator repo url, can be used in tests"
        type: string
        required: false
    secrets:
      registry-username:
        required: true
      registry-token:
        required: true
      cicd-gh-token:
        required: true
    outputs:
      docker-tag:
        description: "Docker tag used to build images"
        value: ${{ jobs.determine_docker_registry_and_tag.outputs.docker_tag }}

jobs:
  determine_ref:
    runs-on: ubuntu-latest
    steps:
      - run: |
    outputs:
      github_ref_name: ${{ inputs.ref-name || github.ref_name }}
      github_ref_type: ${{ inputs.ref-type || github.ref_type }}
  determine_docker_registry_and_tag:
    needs: determine_ref
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - if: needs.determine_ref.outputs.github_ref_type == 'branch'
        name: Determine docker registry and tag (when git branch)
        run: |
          echo DOCKER_REGISTRY=${{ inputs.registry-internal }} | tee -a $GITHUB_ENV
          echo DOCKER_TAG=$(git rev-parse --short HEAD) | tee -a $GITHUB_ENV  # short git commit hash
      - if: needs.determine_ref.outputs.github_ref_type == 'tag'
        name: Determine docker registry and tag (when git tag)
        run: |
          echo DOCKER_REGISTRY=$(echo ${{ needs.determine_ref.outputs.github_ref_name }} | sed 's/network-operator-//' | grep -q '-' && echo ${{ inputs.registry-internal }} || echo ${{ inputs.registry-public }}) | tee -a $GITHUB_ENV  # use public registry only when release tag has no '-beta*' or '-rc*' suffix
          echo DOCKER_TAG=${{ needs.determine_ref.outputs.github_ref_name }} | tee -a $GITHUB_ENV
      - name: Store docker registry and tag for following jobs
        id: store-docker-registry-and-tag
        run: |
          echo DOCKER_REGISTRY=$DOCKER_REGISTRY >> $GITHUB_OUTPUT
          echo DOCKER_TAG=$DOCKER_TAG >> $GITHUB_OUTPUT
    outputs:
      docker_registry: ${{ steps.store-docker-registry-and-tag.outputs.DOCKER_REGISTRY }}
      docker_tag: ${{ steps.store-docker-registry-and-tag.outputs.DOCKER_TAG }}

  build_and_push_images:
    needs: determine_docker_registry_and_tag
    runs-on: ubuntu-latest
    env:
      BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le
      DOCKER_REGISTRY: ${{ needs.determine_docker_registry_and_tag.outputs.docker_registry }}
      DOCKER_TAG: ${{ needs.determine_docker_registry_and_tag.outputs.docker_tag }}
    strategy:
      matrix:
        component: ${{ fromJSON(inputs.components) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-token }}
      - uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
          context: .
          file: ${{ matrix.component.dockerfile }}
          tags: ${{ env.DOCKER_REGISTRY }}/${{ matrix.component.imageName }}:${{ env.DOCKER_TAG }}
          push: true

  update_network_operator_values:
    needs:
      - determine_ref
      - determine_docker_registry_and_tag
      - build_and_push_images
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ needs.determine_docker_registry_and_tag.outputs.docker_registry }}
      DOCKER_TAG: ${{ needs.determine_docker_registry_and_tag.outputs.docker_tag }}
      GH_TOKEN: ${{ secrets.cicd-gh-token }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}-fork
          token: ${{ secrets.cicd-gh-token }}
      - name: Determine base branch
        run: |
          if [[ "${{ needs.determine_ref.outputs.github_ref_type }}" == "branch" || "${{ needs.determine_ref.outputs.github_ref_name }}" == *"beta"* ]]; then  # branch commits and beta tags update values on network-operator's *master* branch
            echo BASE_BRANCH=master | tee -a $GITHUB_ENV
          else  # GA and `-rc.` tags update values on network-operator's respective *release* branches
            release_branch=$(echo ${{ needs.determine_ref.outputs.github_ref_name }} | sed -E 's/^network-operator-([0-9]+\.[0-9]+).+/v\1.x/')  # example: transforms "network-operator-25.1.0-beta.2" to "v25.1.x"
            echo BASE_BRANCH=$release_branch | tee -a $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{inputs.network-operator-repo || 'network-operator'}}
          ref: ${{ env.BASE_BRANCH }}
          token: ${{ secrets.cicd-gh-token }}
          path: network-operator-fork
      - name: Create PR to update image tags in network-operator values
        env:
          COMMIT_MESSAGE: "cicd: update ${{ github.repository }} images tags to ${{ env.DOCKER_TAG }} in chart values"
        run: |
          cd network-operator-fork

          git config user.name  ${{ inputs.service-account-username }}
          git config user.email ${{ inputs.service-account-email }}

          git checkout -b feature/update-${{ github.repository }}-tags-to-${{ env.DOCKER_TAG }}

          # TODO helm chart is a specific case, needs additional work
          #          rm -rf deployment/network-operator/charts/sriov-network-operator/*
          #          cp -r ../sriov-network-operator-fork/deployment/sriov-network-operator-chart/* deployment/network-operator/charts/sriov-network-operator/
          #          # we *don't* copy `Chart.yaml` with the files below, because network-operator's `Chart.yaml` refers to the SR-IOV chart name with a hardcoded version.
          #          git checkout -- deployment/network-operator/charts/sriov-network-operator/Chart.yaml

          # Use jq to parse and iterate over the JSON array
          echo '${{ inputs.components }}' | jq -c '.[]' | while read -r item; do
            name=$(echo "$item" | jq -r '.name')
            yq -i ".$name.repository = \"${{ env.DOCKER_REGISTRY }}\""  hack/release.yaml
            yq -i ".$name.version    = \"${{ env.DOCKER_TAG }}\""       hack/release.yaml
          done

          make release-build

          if ! git diff --color --unified=0 --exit-code; then
          # TODO helm chart is a specific case, needs additional work
          #  git add deployment/network-operator/charts/sriov-network-operator
            git add -u
            git commit -sam "$COMMIT_MESSAGE"
            git push -f -u origin feature/update-${{ github.repository }}-tags-to-${{ env.DOCKER_TAG }}
            gh pr create \
              --repo ${{ github.repository_owner }}/${{inputs.network-operator-repo || 'network-operator'}} \
              --base $BASE_BRANCH \
              --head $(git branch --show-current) \
              --title "$COMMIT_MESSAGE" \
              --body "Created by the *${{ github.job }}* job."
          fi